### ISSUE TITLE
Rounding in the legend

### ISSUE THREAD

**Issue by danielsjf** [GuangchuangYu/scatterpie#3]
I have some issues with your rounding in the legends. If the different radii are orders of magnitude apart, the rounding is not consistent, which seems to lead to a non-natural legend.

![image](https://cloud.githubusercontent.com/assets/6696142/22829458/0724f388-efa3-11e6-85e1-6b556ce888c3.png)

Things can get even worse when two roundings lead to the same number:

![image](https://cloud.githubusercontent.com/assets/6696142/22829574/88fc3614-efa3-11e6-9154-acc00f2f2cea.png)

Maybe you can round all the radii to the same number of digits?

Furthermore, there are some base-R rounding functions available (I saw that you implemented your own function).
https://stat.ethz.ch/R-manual/R-devel/library/base/html/Round.html

**Comment by danielsjf** [comment]
An even better example is this one:

![image](https://cloud.githubusercontent.com/assets/6696142/22829869/d16547e6-efa4-11e6-880b-cbdcec9cf435.png)

Radii: 0.7792073 0.6600432 2.2452716 1.8896772 1.9545808 1.1000840 1.7399760 1.1673637

**Comment by GuangchuangYu** [comment]
the updated version (0.0.6) is not available on CRAN. 😃

**Comment by GuangchuangYu** [comment]
the updated version (0.0.6) is now available on CRAN. 😃
