### ISSUE TITLE
Cannot install scatterpie package

### ISSUE THREAD

**Issue by OceanBridges** [GuangchuangYu/scatterpie#34]
Hi,

I'm experiencing trouble installing this package. I tried both
devtools::install_github("GuangchuangYu/scatterpie")
install.packages("scatterpie")

and not of them works

I'm on R studio Version 1.2.5033

Thanks in advance

Mar

**Comment by GuangchuangYu** [comment]
any error?

**Comment by RowanDurrant** [comment]
Hi, I'm having the same issue with this error message:

```
Error in parse(outFile) : 

  [file path]/scatterpie/R/geom_scatterpie.R:72:17: unexpected '>'

71:       yvar <- get_aes_var(mapping, 'y0')

72:       df <- df |>

                    ^

ERROR: unable to collate and parse R files for package 'scatterpie'
```


I'm on R version 4.0.2 on a Windows machine, and this error happens both when installing from CRAN and github.

Thanks,
Rowan

**Comment by GuangchuangYu** [comment]
@RowanDurrant the latest version only works with R > 4.1.0 as we used native pipe, the `|>` operator.

**Comment by Mr-Byun** [comment]
Try a lower version of scatterpie.
`install.packages('https://cran.r-project.org/src/contrib/Archive/scatterpie/scatterpie_0.1.7.tar.gz', repos=NULL, type='source')`
