### ISSUE TITLE
geom_scatterpie Removal of Black Radius Line for 100% pies

### ISSUE THREAD

**Issue by Keaan95** [GuangchuangYu/scatterpie#4]
Dear author,

Thank you for this page. Ever since ggsubplot was removed from CRAN, the scatterpie package has become invaluable.

For pies where I have 100%, is it possible to remove the radius black line.

I have done color=NA in my geom_scatterpie function but to keep the outline border and just remove the radius line, is it possible?

**Comment by GuangchuangYu** [comment]
No. it is impossible.

**Comment by hmoral** [comment]
Hello GuangchuangYu,

Great functions! very useful! I was wondering is is possible to use specific colour for the pie charts from geom_scatterpie() I tried + scale_colour_manual(value=COLORS)
But it did not worked. Any ideas?

**Comment by GuangchuangYu** [comment]
try `scale_fill_manual(value=COLORS)`

**Comment by hmoral** [comment]
it worked! Thanks

**Comment by kbannarm** [comment]
Is there a way to indicate some pies by group, i.e. have a coloured border on the pies, indicating their group membership?

**Comment by Kailewang** [comment]
> Dear author,
> 
> Thank you for this page. Ever since ggsubplot was removed from CRAN, the scatterpie package has become invaluable.
> 
> For pies where I have 100%, is it possible to remove the radius black line.
> 
> I have done color=NA in my geom_scatterpie function but to keep the outline border and just remove the radius line, is it possible?

Hi @keaan95 , not sure if you have found the solution for this. I also met similar issue recently, the way I did was I draw another layer scatterpie with settings (color=NA and a tiny bit of smaller radius) on top of the original scatterpie. something like:  `ggplot()+ geom_scatterpie(data=clst.xy, aes(x=x, y=y, r=radius*1.2), cols=c("bg1","bg2"), color="black")+ geom_scatterpie(data=clst.xy, aes(x=x, y=y, r=radius*1.18), cols=c("bg1","bg2"), color=NA)`
