### ISSUE TITLE
Changing radius in ggmap

### ISSUE THREAD

**Issue by hditt33** [GuangchuangYu/scatterpie#8]
Hi!
I am using your package in combination with ggmap and I really like it. I only have a problem that when I adjust the radius the pies disappear completely. Is the radius change not compatible with ggmap somehow? If so, is there another way to change the size of the pies?

Best,
Hannes

**Comment by GuangchuangYu** [comment]
any reproducible example?

**Comment by GuangchuangYu** [comment]
the value is just too large, try:

```r
ggmap(map)+geom_scatterpie(data=data,aes(x=long,y=lat,r=radius/100),cols=c("A","B"))
```

**Comment by hditt33** [comment]
Great! Thank you very much!
